### ISSUE TITLE
parse merkle based attestations

### ISSUE THREAD

**Issue by weiwu-zhang** [TokenScript/attestation#1]
Step 1. Provide a merkle tree based test data.
Step 2. Write parsing contracts which successfully validates against the said test data.

Thank you Sangalli for setting out a branch for this. I'll provide my test cases in the branch you made `merkle-tree-attestation`

**Comment by colourful-land** [comment]
@James-Sangalli  I have provided the sample data which can be easily organised into a test case. Kindly check `ethereum/lib/requires_attestation.sol`.

**Comment by weiwu-zhang** [comment]
closing this issue as we moved to zk based protection mechanism.
