### ISSUE TITLE
Implement Eip712 signing for all cases where the user needs to sign

### ISSUE THREAD

**Issue by jot2re** [TokenScript/attestation#112]
So far the reference implementation only uses EIP712 for web authentication. To make the whole flow user-friendly and pretty this message format should be implemented all places where the user needs to sign. This includes:
1. Attestation request.
2. Attested object.

**Comment by colourful-land** [comment]
User-friendliness is not the only thing we should watch for. Today's transaction costs $80 USD easily. Gas....

When authenticating for the web, or doing capability attestation, there is no gas consideration so we should maximise user experience

**Comment by jot2re** [comment]
Auch! That is a huge price increase. I still think item 1 is valid, since this is never going to be posted to the blockchain as you also point out. In regards to item 2  it is currently only used unsigned in the webauthentication flow (since it is just a component of what is signed). So with you comment in mind I think we should not touch the signing of this (at least for now).
I am also realising another issue with using EIP712 and DER together. The DER encoded content will not make sense in the EIP712 interface and thus the relevant, human-readable aspects of what is DER encoded should then be included in the EIP712 message which will make the message even bigger...

**Comment by jot2re** [comment]
Closed (so far) by PR #113
