### ISSUE TITLE
remove the signing of useTicket 

### ISSUE THREAD

**Issue by colourful-land** [TokenScript/attestation#153]
I think during the devcon demo I noticed useTicket being signed. if it is true, it should be skipped. both the smart contract and the front end should allow useTicke to be used without signed.

on another note, useTicket should be different for each transaction bounce, but that can be done in a separate issue.

**Comment by oleggrib** [comment]
currently useTicket just combined ticket+attestation+proof without signature and it always same while attestaion not expire
useEthKey contains signature of the challenge

**Comment by jot2re** [comment]
I agree with @oleggrib regarding this issue. But even though adding the signature ensures that the useTicket is different each time, it is still possible to reuse an old useTicket as it remains valid.  However as we have briefly discussed a bit previously simply adding an unpredictable to the proof can ensure that it is unique each time and that it can be linked to a specific use context. The java code is already prepared to take such a parameter and thus can be easily adapted
