### ISSUE TITLE
Update Solidity code according to bug fixes

### ISSUE THREAD

**Issue by jot2re** [TokenScript/attestation#196]
A few bug-fixes have been implemented on the DevCon Ticket and magicLinks.
The Solidity code needs to be updated accordingly. 
See issue #192 and its PR #194 for details.
Furthermore, issue #193 and PR #195 might also be relevant.

Concretely the issue can be seen since `org.devcon.ticket.UseTicketTest.testSmartContractDecode` fails, due to the ASN1 encoding format having changed on the Ticket object.

**Comment by weiwu-zhang** [comment]
2 actions already done.
