### ISSUE TITLE
Make NFTAttestation Request EIP712

### ISSUE THREAD

**Issue by jot2re** [TokenScript/attestation#209]
[Per request](https://github.com/AlphaWallet/AlchemyNFT/issues/143#issuecomment-974513130) from @JamesSmartCell  and for general convenience the NFTAttestation request should be done using EIP712.

**Comment by jot2re** [comment]
@oleggrib I will do this in Java, but I think it will also involve a bit of JS update afterwards unfortunately. I will ping you when needed.

**Comment by hboon** [comment]
@jot2re wrong James :)
