### ISSUE TITLE
TypeError: Cannot convert a BigInt value to a number

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/attestation#217]
![Screen Shot 2021-12-17 at 2 10 04 pm](https://user-images.githubusercontent.com/6808817/146482837-5e01b460-176e-4616-a7fc-cf126f1798f9.png)

Attestation JS Library.

**Comment by nicktaras** [comment]
var E = Math.pow(Number(2n), Number(256n)); - Solution is to convert all the BigInt values to numbers before use.

**Comment by nicktaras** [comment]
@oleggrib this method given above is a solution to allow for BigInt to be safely cast as a number.

Can you take a look at updating the authenticator to use this when using BigInt?

Thanks 

Nick

**Comment by oleggrib** [comment]
@nicktaras , looks like its fixed. can you confirm?

**Comment by jot2re** [comment]
@nicktaras confirms this is no longer relevant.
