### ISSUE TITLE
Create release flow to eliminate need for snapshots

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/attestation#218]
The task is from TokenScript but dependency on attestation.id

Requirement is a flow to define how and when we can release a package to npm (js code) or maven (java code).

in a summary, it is about how to make release plan and automate it. currently, no such things.

**Comment by micwallace** [comment]
@nicktaras I agree that we should package the libs folder to make core attestation logic available to both TN and attestation.id.

**Comment by jot2re** [comment]
I am closing this since it is handled with PR #239
