### ISSUE TITLE
Liscon Improvements

### ISSUE THREAD

**Issue by AW-STJ** [TokenScript/attestation#220]
- [x] Dialog box: UI Tweaks 

![image](https://user-images.githubusercontent.com/61957841/146925002-79715d25-8e08-4c1c-82a5-d5cfa2d8b776.png)

- [x] Dialog box: Updated message for network switch

![image](https://user-images.githubusercontent.com/61957841/146925056-8b1fb523-680c-4230-a733-a60f85c877a4.png)
**Proposed text:** 
Confirm network change on Metamask 

- [x] Dialog box: Updated message for connecting Metamask

![image](https://user-images.githubusercontent.com/61957841/146925250-c2c3f315-d793-434d-a2ea-9505bb9403f6.png)

**Proposed text:** 
Note: You might be prompted to connect Metamask again to complete the process

- [x]  Dialog box: Updated message for minting NFT

![image](https://user-images.githubusercontent.com/61957841/146925426-eee43ad0-9b06-4a5e-b6e5-95256be06781.png)

**Proposed text:** 
Confirm transaction to mint Liscon proof of ticket NFT for 'Ethereum Rinkeby Testnet'

The network names for mainnets can be : just Ethereuem, Polygon, Arbitrum, Optimistic etc. 

- [x] Background colour for Attestation.id modal

The current attestation.id modal has a white background... is there a way to make it dark. Not sure whether it is possible. but just a question to consider.
![image](https://user-images.githubusercontent.com/61957841/146926084-a0a1a697-5428-417a-b101-8785121a5017.png)

- [x] Update Smart Token Labs details
![image](https://user-images.githubusercontent.com/61957841/146929017-c779e6ba-bbe0-4441-9909-1913807b39f8.png)

**Comment by oleggrib** [comment]
> **Proposed text:**
> Confirm network change on Metamask

@AW-STJ 
Out of the box Metamask includes only Ethereum mainnet and testnets. In case if we want to use some other networks like Optimism/Poligon/etc.. then we have to add new network to the Metamask and then change current network to the New one. So we need both messages: "Add network", "Switch/change network"

**Comment by AW-STJ** [comment]
> @AW-STJ
Out of the box Metamask includes only Ethereum mainnet and testnets. In case if we want to use some other networks like Optimism/Poligon/etc.. then we have to add new network to the Metamask and then change current network to the New one. So we need both messages: "Add network", "Switch/change network"

Then let the text be "Confirm the network on Metamask". Need not specify whether its addition or switch etc. I am trying to reduce the text. If Devcon team says otherwise, then we can change the text.

> But before use it with mainnet we have to deploy contracts to the mainnets. (simple action, but need PrivateKey of accaount with appropriate ETH)

Okay, will get you the ETH required. Let me know how much it would be.

> @foxgem can change background color (he need color code and he has to change fonts to the white and invert some
other page elements) , it will affect only liscon attestation website, not legacy attestation.id

What I meant here is to change the background for the iFrame like a modal. Not sure whether this is possible or not.
![image](https://user-images.githubusercontent.com/61957841/147174944-591a39a2-04ff-4096-997c-a52a2810b375.png)

Not a must have, but a good to have. Let me know whether its hard to implement this.

**Comment by foxgem** [comment]
we can not control this because the iframe is called by the parent site. I guess the iframe is shown in a modal, if so, the parent site can control this.

**Comment by AW-STJ** [comment]
Thanks @foxgem for the response. @oleggrib - let us do it if that is possible and not hard to implement. If its harder and takes more time, then we can ignore this requirement.

**Comment by oleggrib** [comment]
@AW-STJ ,  styles and logos updated

> Okay, will get you the ETH required. Let me know how much it would be.

let me check how to use ledger for deploy contracts.

**Comment by oleggrib** [comment]
@AW-STJ , I have ready code to use Ledger for different networks, so we can use tokens safely and deploy to the some mainnets

**Comment by weiwu-zhang** [comment]
Closing since all sub tasks are closed. Reopen if the sub-issues are not properly merged into main workstream.
