### ISSUE TITLE
Change Ticket_ID to String from integer 

### ISSUE THREAD

**Issue by AW-STJ** [TokenScript/attestation#221]
Request from Devcon to change  ``ticket_id``  integer to a string. MIght be related to #115, but really to make it more flexible for future as well as to prevent a inelegant implementation of TicketID decoding for our current Liscon implementation.

**Comment by jot2re** [comment]
@oleggrib @JamesSmartCell I will update this in Java, but I think I need your help to adjust the Solidity and JS versions accordingly. 
Furthermore, it is also important that we still have backwards compatibility and can understand the old tickets where the ID is an integer.

**Comment by oleggrib** [comment]
@jot2re , we can set field devconId to variable( CHOISE ), so we can use Integer or String here. Its compatable with ASN1 so no problems here.
For JS we can read Integer/BigInt as string.
in case of solidity validation contract it need more work to update.
cc @colourful-land @JamesSmartCell

**Comment by jot2re** [comment]
Yes, agree there is no issue when it comes to a complete ASN specification. 
Cool, that it should directly with JS.

**Comment by jot2re** [comment]
I have made the java change in PR #225

**Comment by jot2re** [comment]
@oleggrib please ensure that things also work in the JS 
@JamesSmartCell the smart contract code will also need to be updated to ensure understanding of tickets where the ticket ID is a string. It might be relevant to do this as a separate task though

**Comment by oleggrib** [comment]
I just added commit for JS code. I think we can merge and @JamesSmartCell can update validation contract when we need to use it.

**Comment by jot2re** [comment]
I have merged in the Java code, see PR #225, if we want to run with this change then the smart contract probably needs to be updated as well, but currently everything should be backward compatible @JamesSmartCell

**Comment by JamesSmartCell** [comment]
Is this still pending?

**Comment by JamesSmartCell** [comment]
> > Is this still pending?
> 
> As far as I can see, you handle it in #243, right?

Yes, that PR should close this issue.
