### ISSUE TITLE
Verification contract have to compare twitterID (numeric ID), not whole string uncluding twitter name

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/attestation#224]
Twitter User can easy change his name but account stay the same, so we have to make sure that verification contract compares only twitterId part, not twitter name.
@JamesSmartCell , can you confirm that?
cc @colourful-land

**Comment by JamesSmartCell** [comment]
That's correct; and we do use the full ID in the attestation (or at least, we should be - the prototype used the full ID including the numeric ID).

**Comment by weiwu-zhang** [comment]
There is no known case in the smart contract where the verification compares one identifier attestation with another one to see if it attests the same user.
