### ISSUE TITLE
liscon.attestation.id doesnt work with walletconnect under android

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/attestation#230]
On android it doesnt work with WalletConnect
![image](https://user-images.githubusercontent.com/18176173/153947406-c29d7000-a159-42a0-81ac-4f40574c571a.png)
Step to reploduce:
- clear liscon.attestation.id domain localstorage
- open liscon.attestation.id in chrome
- click Browser Wallet
- click WalletConnect
it throws error and nothing happens.

**Comment by foxgem** [comment]
wc provider used is deprecated, it can be fixed by update the version to the latest.
