### ISSUE TITLE
liscon.attestation.id displays wrong input field type for android

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/attestation#231]
I have to enter OTP 580316, but It displays only 1,2,3,7,9 and no way to scroll or enter number with keyboard
![image](https://user-images.githubusercontent.com/18176173/153947887-de9f5e3b-2277-4931-859b-553cbf909b0c.png)

**Comment by foxgem** [comment]
turned off `autocomplete`, now it seems ok:
![image](https://user-images.githubusercontent.com/304052/153985741-c839c8db-54a1-43ad-b800-0b81d6ad5fea.png)

**Comment by abcfy2** [comment]
https://liscon.attestation.id/ redeployed. You may try again later.
