### ISSUE TITLE
reïnsert the tests abandoned during liscon tickets

### ISSUE THREAD

**Issue by jot2re** [TokenScript/attestation#254]
We need to get hardhat integration tests up as part of our CI/CD.
In particular, due to lack of saving keys and updated format, we have had to completely remove some hardhat tests in the setting of Liscon tickets.  See PR #243 
These should at a minimum be redone (in a way that makes it easy to update in case we end up changing the format).

**Comment by weiwu-zhang** [comment]
@abcfy2 do you know the hardhat testing flow?

**Comment by foxgem** [comment]
> do you know the hardhat testing flow?

doesn't hardhat support test? if there are the testcases for the contracts, it is easy to add a github action to kick off it with hardhat command: `npx hardhat test`.

**Comment by jot2re** [comment]
Yes, hardhat supports tests. However, they have not been set up in an optimal manner. I.e. they use hard-coded signed object where the test keys have never been saved. Hence many of the tests have been out-commented as formats of signed objects have changed. 
Hence this task is about reenable, refactor and perhaps expand the tests in a way way where they are easy update and expand.
Furthermore, they are also not currently being executed as a GitHub task, but as you say, setting that up is the easy part of this task 😅

**Comment by jot2re** [comment]
Although as @weiwu-zhang has pointed out to me, adding these to CI/CD should be part of issue #244

**Comment by jot2re** [comment]
@oleggrib yes, that is no problem. There is also no problem with hardcoded test-keys. The problem with the old hardhat tests were that signed objects were hardcoded and signed with a private test key which was not saved. Since the format of objects had changed everything needs to be set up and generated again. I think the best is simply to store the code for generating these things and keeping the private test keys hardcoded in the tests.

**Comment by oleggrib** [comment]
@jot2re , by the way - I always try to add fallback random private key, so even if  .env is missing then hardhat still can pass tests, so in most cases no need to change something, even more - currently in this repo hardhat tests are passing OK

**Comment by jot2re** [comment]
I think we might be misunderstanding each other @oleggrib. What happened was that I had to outcomment a lot of hard hat tests awhile ago because they were based on base64 encoded objects, but the structure of that object had changed. Hence leaving out the tests was a quick fix instead of writing code to generate new object and adjusting the tests :)
So this task was originally simply intended to fix all those out-commented tests.
But in any case you are right, there there should not be any need to use values in .env for running the hardhat tests.

**Comment by oleggrib** [comment]
we dont use Liscon flow nomore, so I think no need to supprt Liscon tests. LisCon updated to devconnect. @jot2re @AW-STJ

**Comment by jot2re** [comment]
Ah, right. Sorry. I don't remember if everything was Liscon specific, but if it is, then you are right that the out-commented tests are no longer an issue.

**Comment by jot2re** [comment]
Closing since the relevant code for this is obsolete
