### ISSUE TITLE
Entropy source for unpredictable numbers is guessable

### ISSUE THREAD

**Issue by jot2re** [TokenScript/attestation#269]
The Heruko crypto-verify needs to be able to construct unpredictable numbers. This requires a high entropy key, in order to yield the security guarantees required for an unpredictable number. However the key used is a 3 digit number. Hence without any entropy. It should be replaced with a high entropy key stored in an environment variable.

See section 2.5.4 in the NFT Minting security report.
[See Jira issue 291.](https://smarttokenlabs.atlassian.net/browse/PR-291)

**Comment by oleggrib** [comment]
3 digit number it was a password(key) to hash messages. 

secret generated in the UnpredictableNumberTool constructor: crypto.randomBytes(UnpredictableNumberTool.BYTES_IN_SEED)

is it OK? @jot2re

**Comment by oleggrib** [comment]
@jot2re , ok, I got it.
so many bytes must be the KEY to stay service secure?

**Comment by jot2re** [comment]
At least 16 bytes. Preferably 32 bytes.

**Comment by oleggrib** [comment]
key updated to 32bytes. you can see it in the heroku app settings

**Comment by jot2re** [comment]
Great! Thanks @oleggrib
