### ISSUE TITLE
Build a lambda that takes a signing request and returns an attestation to be stored locally

### ISSUE THREAD

**Issue by AW-STJ** [TokenScript/attestation#31]
Trulioo JSON Response File:
[identityVerificationResponse.json.txt](https://github.com/AlphaWallet/blockchain-attestation/files/5252970/identityVerificationResponse.json.txt)

Latest iteration of swimlane of the process:
![image](https://user-images.githubusercontent.com/61957841/94798557-1fdfe500-0425-11eb-8f28-4d055b1dbc76.png)

**Comment by AW-STJ** [comment]
Also sharing the wireframes of the KYC Screens, that captures the information to be passed on to Trulioo:
![image](https://user-images.githubusercontent.com/61957841/93725864-dbb73e00-fbf5-11ea-8aa1-5cb84ff39e8d.png)

**Comment by jot2re** [comment]
Obsolete, will close.
