### ISSUE TITLE
Build a dummy certificate signing request JavaScript

### ISSUE THREAD

**Issue by AW-STJ** [TokenScript/attestation#32]
# New Requirement

Build CSR for identifier attestation to be used in attestation.id

# Old Requirement

(Old Requirement was abandoned thanks to the way Trulioo works)

----

This should be the real service that will replace the dummy service that will be created:
https://github.com/AlphaWallet/blockchain-attestation/issues/31

Trulioo JSON Response File:
identityVerificationResponse.json.txt

Latest iteration of swimlane of the process:
image
![image](https://user-images.githubusercontent.com/61957841/93725936-83347080-fbf6-11ea-8a56-605e8bf697f4.png)

wireframes of the KYC Screens, that captures the information to be passed on to Trulioo:
image
![image](https://user-images.githubusercontent.com/61957841/93725930-79ab0880-fbf6-11ea-940c-cdd7be8fb1aa.png)

**Comment by jot2re** [comment]
Obsolete, will close.
