### ISSUE TITLE
Reduce tansaction size: by not including the signature in UseTicket

### ISSUE THREAD

**Issue by colourful-land** [TokenScript/attestation#47]
The reason is that when the structure is used for a smart contract, the whole transaction is signed anyway by Bob, which includes the UseTicket or RedeemCheque, and being able to save a signature (and its verification) does matter when it comes to smart contract verification.

When the signatures are needed thanks to the structure being used on the web, we can add it then (e.g. making it optional). How do you think?

**Comment by jot2re** [comment]
I think (but I need to think a bit more about it) that is should be OK in our setting not to include the signature. However, this does allow for a mix-and-match attack by a man-in-the middle. (I.e. it allows a miner to try to combine a proof, attestation and ticket in a way not intended by the user). But if whatever the transaction is used for is strongly linked to the attested Ethereum address then this should not pose a security risk.

**Comment by jot2re** [comment]
We are sticking with the signature for now, right @colourful-land ?

**Comment by colourful-land** [comment]
> We are sticking with the signature for now, right @colourful-land ?

The transactions are too fat. I think we should go for making the signature optional in the UseTicket (reason for not excluding it: I think including signatre in UseTicket is useful in 2-party authentication instead of the blockchain?).

To put in to the context, I hope we can do a project to solve this together with #69 and #70

**Comment by jot2re** [comment]
Disregard my previous comment about mix-and-matching. It should not be an issue since the transaction will be signed by the user before it reaches the miner.

**Comment by jot2re** [comment]
This is closed by PR #89
