### ISSUE TITLE
JavaScript parser for SignedTicket

### ISSUE THREAD

**Issue by colourful-land** [TokenScript/attestation#48]
1) Run the test-cases (or reach out to @jot2re if you need support in that) in order to get some binary (DER) data for a piece of SignedTicket.

2) Write the JavaScript needed to parse it and return an object that has the members such as:

https://github.com/AlphaWallet/blockchain-attestation/blob/5ab6174d3e17f209cca897d0ce91937ccf1d8ba0/data-model/SignedTicket.asn#L17-L19

3) However, do not return riddle as is, see if you can return it as an instance of `Point`. For this, you need the [Point class](https://github.com/AlphaWallet/blockchain-attestation/blob/secp256k1-utility-class/esm/secp256k1.ts). Therefore, it's perhaps better fork a branch from the `secp256k1-utility-class` branch. See if the points (which are made of `(x,y)`) is the same as the one used in Java test cases.

(To provide some context on where is this to be used: the object which has attributes such as ticketClass is this the `ticketToken` in this example code):
http://docs.tokenscript.org/guide-attestation/issuer-site.html

----

The data module is here:

https://github.com/AlphaWallet/blockchain-attestation/blob/master/data-model/SignedTicket.asd

https://github.com/AlphaWallet/blockchain-attestation/blob/master/data-model/SignedTicket.asn

----

Note: if https://github.com/PeculiarVentures/ASN1.js is not suitable for this job, let us know early why.

**Comment by darakhbharat** [comment]
Hi Weiwu,

I have created new branch named **asn1js-development** and pushed initial version of JS code which parses the DER encoded data.

Right now I have created small pem file from SignedObjects.pem given by @jot2re. and extracted ticket(ticketClass, ticketId, conferenceId) object. Riddle part is not done yet.

To RUN the JS code open asn1js/public/index.html file in browser and upload attached SignedTicket.pem file. Need to extract the file from ZIP package.

[SignedTicket.zip](https://github.com/AlphaWallet/blockchain-attestation/files/5701692/SignedTicket.zip)

I have not yet used the magic link, Do I need to pick the data from magic link instead of pem file?

**Comment by jot2re** [comment]
@darakhbharat both TICKET_ID, TICKET_CLASS, CONFERENCE_ID and TICKET_SECRET are integers, I.e. as specified in [this ASN1 file](https://github.com/AlphaWallet/blockchain-attestation/blob/master/data-model/SignedTicket.asn). ATTESTATION_SECRET is an Octet String instead.
The value of the riddle is computed from ATTESTATION_SECRET and MAIL and thus not given as argument.

The blockchain-attestation is a standard Gradle project that will dynamically download any needed dependencies when you build it. However, if you don't have a Java IDE setup and not worked with it before it will probably take a bit to get to work. So I will include some other example encodings below

**Comment by oleggrib** [comment]
https://github.com/AlphaWallet/blockchain-attestation/blob/secp256k1-utility-class/esm/ts/src/libs/DerUtility.ts
we can use my code to decode ASN1DER . I have added support dor basic types that we need for "createCheque" and "requestAttestation". I can easy extend it to support other data types.

**Comment by colourful-land** [comment]
> https://github.com/AlphaWallet/blockchain-attestation/blob/secp256k1-utility-class/esm/ts/src/libs/DerUtility.ts
> we can use my code to decode ASN1DER . I have added support dor basic types that we need for "createCheque" and "requestAttestation". I can easy extend it to support other data types.
> Create Point() instance its trivial, I think its not related to ASN1DER parser, it can be added in parent code.

did you write that from scratch? Impressive! 

Whatever ASN1 parse/seraliser (which always have a DER reader/writer, like your DER reader in `DerUtility`) we choose to use, it must support dynamic typing eventually, and @darakhbharat thought of an XSLT way to do that back in May 2020 but hasn't implemented such. Read the discussion at that time https://community.tokenscript.org/t/parsing-der-with-asn1-modules-provided-runtime/375/3

The reason being the next project (other than DevCon - one example being CO2 token) might issue attestations of their customised data (e.g. CO2 credit), which we can't hard-code JavaScrpit for. Better they write the data module, and we generate the asn1 parser/serialiser programmatically. In this project, there is no harm to hard code an asn1 parser/serialiser since every partner who will do attestation based on devcon will be able to reach us and ask for a customization JavaScript but the choice of library should be with the view of eventually making it work with different schemas at runtime.

**Comment by darakhbharat** [comment]
Hi Weiwu,

I have checked in In-development version of the decoder in new branch called **asn1js-development**.
One can open the index.html in the browser and paste the SignedTicket object encoded DER string in the textarea and click outside of the textarea( to trigger on change event.)

Right now the program is extracting ticketId, ticketClass, conferenceId but not the riddle. I am looking into it but not able to make any progress yet. I am not seeing the riddle information returned from asn1js. Can you pick this up to complete the riddle stuff? 

	
Please refer below screen shot.
![image](https://user-images.githubusercontent.com/20576109/103133708-cd206d00-46a3-11eb-84bf-d2f2cd8ce5cd.png)

**Comment by jot2re** [comment]
@darakhbharat there has now been a couple of small changes to the ticket format. Furthermore, I have made an update to ensure that all java tests are deterministic. So after PR #59 and PR #60 gets merged it should become easy to verify that things get parsed correctly in the JS implementation.

**Comment by colourful-land** [comment]
Solved by https://github.com/TokenScript/attestation/pull/62
