### ISSUE TITLE
 contract test does not work since James have not updated the solidity code yet to work with the BN256 and Pedersen commitments

### ISSUE THREAD

**Issue by colourful-land** [TokenScript/attestation#56]
This line in TestPoK.java

      assertTrue(sc.testEncoding(pok));

**Comment by jot2re** [comment]
I have not had this issue so far, but the code running this test is written by @JamesSmartCell as it is the code that integrated with the blockchain. Maybe you can have a look at this @JamesSmartCell ?

**Comment by jot2re** [comment]
Closed by #111
