### ISSUE TITLE
instantiate data object through magic link

### ISSUE THREAD

**Issue by colourful-land** [TokenScript/attestation#80]
This is where the Java code produce the test URL
https://github.com/TokenScript/attestation/blob/dee1a23d36911169686bfab12d141a034423d003/src/test/java/com/alphawallet/attestation/ticket/TestTicket.java#L64

This issue is considered solved when the test case works. Currently in `data-object-from-magic-link ` branch:

````
$ gradle testJavaScript
Configuration on demand is an incubating feature.

> Task :testJavaScript FAILED
SignedDevconTicket {
  ticket: DevconTicket { devconId: 6n, ticketId: 48646n, ticketClass: 0n },
  commitment: ArrayBuffer {
    [Uint8Contents]: <04 0a fd f0 e2 47 4c ae 9b 66 16 f0 4b ac dd 9f 76 ab 58 82 db b8 39 9d 3f 60 a1 53 61 da d7 03 0f 27 be 3f 58 3f e4 5d e9 49 5f 84 f4 82 37 ec 2b 7c 71 0e b3 b5 d2 e7 a5 65 2d 8d 56 c7 18 25 6f>,
    byteLength: 65
  },
  signatureValue: ArrayBuffer {
    [Uint8Contents]: <30 44 02 20 38 db 21 b6 b5 b7 c6 92 da ad a2 b6 2e bb 89 e5 a3 6e 3a 3c ce 66 1e 38 53 2b c9 ac c8 5c 34 1b 02 20 70 46 73 21 8f 77 b2 47 b5 51 ab 3c 3d 74 e1 ef 8f 4f 7e 3a e0 40 1d 53 54 26 65 3a aa 5e c2 a2>,
    byteLength: 70
  }
}
file:///home/a/IdeaProjects/attestation/src/main/javascript/SignedDevonTicket.js:117
      throw new TypeError("Unimplemented: Not accepting string yet.")
            ^

TypeError: Unimplemented: Not accepting string yet.
    at new SignedDevconTicket (file:///home/a/IdeaProjects/attestation/src/main/javascript/SignedDevonTicket.js:117:13)
    at file:///home/a/IdeaProjects/attestation/src/test/javascript/ParserSerializerTest.js:19:11
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':testJavaScript'.
> Process 'command '/home/a/IdeaProjects/attestation/.gradle/nodejs/node-v14.15.3-linux-x64/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
6 actionable tasks: 1 executed, 5 up-to-date
````

**Comment by darakhbharat** [comment]
Hi @Weiwu, @Oleh

I was trying the below approach for constructing DevconTicket data object from the magic link.


```
if (typeof(source) == "string") {
      const magicContent = source.substring(source.indexOf('?') + 1);
      const der = Buffer.from(magicContent, "base64");

      const ber = new Uint8Array(der).buffer;

      const ans1ArrayBuffer = fromBER(ber);
      this.fromSchema(ans1ArrayBuffer.result);
    }
```


But then Weiwu remindered about checking how it is done in Java.

I checked corresponding code in 
	- TestTicket.java function testTicketURLSunshine and 
	- URLUtility.java function decodeData.

Then 

I referred the code from @Oleh here - [](https://github.com/TokenScript/attestation/blob/secp256k1-utility-class/esm/ts/src/libs/DerUtility.ts)

and tried to resolve the issue.


I have committed work in progress code in branch data-object-from-magic-link. 

Right now I am getting the error 

```
/attestation/src/main/javascript/SignedDevonTicket.js:247
                throw new Error("Object's schema was not verified against input data for SignedDevconTicket");
                      ^

	Error: Object's schema was not verified against input data for SignedDevconTicket
```
	
When I debugged the code I see data is present in asn1.result variable of line 253 SignedDevconTicket.js but asn1.result.ticket is undefined, 

I am stuck here, @Oleh Can you look into the issue to see if I am on correct path?

**Comment by darakhbharat** [comment]
More findings on this is we may even not need the stuff from the https://github.com/TokenScript/attestation/blob/secp256k1-utility-class/esm/ts/src/libs/DerUtility.ts

as the asn1 library provides the URL decoding already. It has function fromBase64 which is capable of hadling base64URL data.

Here is what I have tried but still not completed.


```
 constructor(source = {}) {
    if (typeof(source) == "string") {

      let urlBase64String = source.substring(source.indexOf('?')+1);
      //const ber = this.readFromUrlBase64String(urlBase64String);

      const ans1fromBase64 = fromBase64(urlBase64String,true);
      const ans1ArrayBuffer = stringToArrayBuffer(ans1fromBase64);
      const asn1 = fromBER(ans1ArrayBuffer);
      this.fromSchema(asn1.result);
    } 
	

```
As Weiwu said there is extra stuff not just base64 encoding. So senderPublicKey is used while encoding how to decode it in JS, Do we need to update the schema with PublickKeyInfo added recently in SignedDevconTicket?

Below is the Java Code:
 ```
byte[] senderPublicKey = SubjectPublicKeyInfoFactory.createSubjectPublicKeyInfo(senderKeys.getPublic()).getPublicKeyData().getEncoded();
 String url = URLUtility.encodeList(Arrays.asList(ticket.getDerEncoding(), senderPublicKey));

 FileWriter fileWriter = new FileWriter(PREFIX + "mah@mah.com.url");	
```

**Comment by colourful-land** [comment]
Getting @jot2re's attention here but the answer how to parse the data once you decoded it is in the Java source code (should be in `TicketDecoder` class)

**Comment by jot2re** [comment]
Yes, `TicketDecoder` shows how to decode a public key. In regards to the question of update to the schema, the answer is also yes. It needs to be consistent with `SignedDevconTicket.asd`/`SignedDevconTicket.asn` in the main branch

**Comment by oleggrib** [comment]
@darakhbharat , this code grab params from URL and prepare buffer for new Ticket.

const magiclink = readFileSync('build/test-results/mah@mah.com.url', 'utf8')
const url = new URL(magiclink);
let searchStr = url.search;
searchStr = searchStr.substr(1);
let base64str = searchStr
    .split('_').join('-')
    .split('/').join('+')
    .split('.').join('=');

dataobj = new SignedDevconTicket(Buffer.from(base64str, 'base64'));

it outputs with:
SignedDevconTicket {
  ticket: DevconTicket {
    devconId: undefined,
    ticketId: undefined,
    ticketClass: undefined
  },
  commitment: undefined,
  signatureValue: undefined
}

does it helps you?
