### ISSUE TITLE
create the web authentication backend at org.tokenscript.auth

### ISSUE THREAD

**Issue by colourful-land** [TokenScript/attestation#99]
Verify SignedDevconTicket (against known pubkey)
Verify MyAttestation (against known pubkey)
Verify the zk proof
Verify the challenge is in the message
Verify the signature is attested by MyAttestation.

The “Message” is signed by wallet (e.g. metamask)
therefore have a prefix. It might be a json array with
Base64 encoded UseDevconTicket:
{“useDevconTicket”: “Ze8zE/==”, “challenge”, “809843…”}

**Comment by oleggrib** [comment]
We have to create some detailed flow of signing message.
Also org.tokenscript.auth have to send verify status to the bogota backend directly 
And I think user have to signWithMetamask message like "Sign Ticket verification hash: 0xc89efdaa54c0f20c7adf612882df0950f5a951637e0307cdcb4c672f298b8bc6"(simple message easy to understand for user, user will see it in Metamask), where hash - keccak256 of the UseDevconTicket

**Comment by jot2re** [comment]
This is fixed by PR #101
